db_url: "postgres://kingyang:@localhost:5432/hestia_development?sslmode=disable"
redis_url: "redis://:@localhost:6379/0"
nats_url: "nats://localhost:4222"
server_url: ":8080"
current_node: "127.0.0.1:8080"
jwt_key: ""
